apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falcon-kac.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: webhook-port
  selector:
    {{- include "falcon-kac.selectorLabels" . | nindent 4 }}
