apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cs-k8s-protection-agent.fullname" . }}
  labels:
    {{- include "cs-k8s-protection-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "cs-k8s-protection-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
    {{- include "cs-k8s-protection-agent.labels" . | nindent 8 }}
    spec:
    {{- if or (.Values.image.pullSecrets) (.Values.image.registryConfigJSON) (.Values.crowdstrikeConfig.dockerAPIToken) }}
      imagePullSecrets:
        {{ if .Values.crowdstrikeConfig.dockerAPIToken }}
        - name: {{ include "cs-k8s-protection-agent.fullname" . }}-regsecret
        {{- end }}
        {{ if .Values.image.pullSecrets }}
        - name: {{ .Values.image.pullSecrets }}
        {{- end }}
        {{ if .Values.image.registryConfigJSON }}
        - name: {{ include "cs-k8s-protection-agent.fullname" . }}-regsecret-registryconfigjson
        {{- end }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name | default ( include "cs-k8s-protection-agent.fullname" . ) }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "cs-k8s-protection-agent.fullname" . }}
            - secretRef:
                {{- if .Values.crowdstrikeConfig.existingSecret }}
                name: {{ .Values.crowdstrikeConfig.existingSecret }}
                {{- else }}
                name: {{ include "cs-k8s-protection-agent.fullname" . }}
                {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.crowdstrikeConfig.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
